# fly.toml app configuration file generated for wildwatchboard on 2026-07-25T04:06:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wildwatchboard'
primary_region = 'sjc'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3001'
  SQLITE_PATH = '/data/wildwatchboard.sqlite'

[[mounts]]
  source = 'wildwatch_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
